51800882_51800187_QLSinhVien/Models/SinhVien.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using _51800882_51800187_QLSinhVien.Res;

namespace _51800882_51800187_QLSinhVien.Models
{
    public class SinhVien
    {
        [Key]
        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredStudentId")]
        [StringLength(5, ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messStringStudentId")]
        [Display(Name = "studentId", ResourceType = typeof(LangResource))]
        public string MaSV { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredFullName")]
        [StringLength(100, ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messStringFullName")]
        [Display(Name = "fullName", ResourceType = typeof(LangResource))]
        public string HoTen { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredBirthday")]
        [Display(Name = "birthDay", ResourceType = typeof(LangResource))]
        [DataType(DataType.Date)]
        [DateValidationAttribute(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messDateValidationAttribute")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime NgaySinh { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredGender")]
        [Display(Name = "gender", ResourceType = typeof(LangResource))]
        public string GioiTinh { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredFaculty")]
        [Display(Name = "facultyId", ResourceType = typeof(LangResource))]
        public string MaKhoa { get; set; }

        [ForeignKey("MaKhoa")]
        public virtual Khoa Khoa { get; set; }

        [JsonIgnore]
        public virtual ICollection<KetQua> KetQuas { get; set; }
    }
}

51800882_51800187_QLSinhVien/Controllers/KetQuaController.cs
using _51800882_51800187_QLSinhVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace _51800882_51800187_QLSinhVien.Controllers
{
    public class KetQuaController : Controller
    {
        // GET: KetQua
        string apiUrl = "https://localhost:44328/api/";

        // Danh sách kết quả
        [Authorize(Roles = "admin, user")] 
        public ActionResult Index()
        {
            var db = new QLSVContext();
            ViewBag.MaMH = new SelectList(db.MonHocs, "MaMH", "TenMH");
            ViewBag.Loai = 0;

            IList<KetQua> kq = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KetQuaAPI");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<KetQua>>();
                    readTask.Wait();

                    kq = readTask.Result;
                }
            }
            return View(kq);
        }

        // Danh sách Kết quả tất cả môn của 1 sinh viên
        [Authorize(Roles = "admin, user")]
        public ActionResult IndexByMaSinhVien(string masv)
        {
            SinhVienDAO svdao = new SinhVienDAO(new QLSVContext());
            ViewBag.Loai = 1;
            ViewBag.TenSV = svdao.GetHoTenByMaSV(masv);
            ViewBag.MaSV = masv;

            IList<KetQua> kq = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KetQuaAPI?masv=" + masv);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<KetQua>>();
                    readTask.Wait();

                    kq = readTask.Result;
                }
            }
            return View("Index", kq);
        }

        // Danh sách kết quả của tất cả sinh viên của 1 môn học
        [Authorize(Roles = "admin, user")]
        public ActionResult IndexByMaMonHoc(string mamh)
        {
            var db = new QLSVContext();
            ViewBag.MaMH = new SelectList(db.MonHocs, "MaMH", "TenMH");

            MonHocDAO mhdao = new MonHocDAO(db);
            ViewBag.Loai = 2;
            ViewBag.TenMH = mhdao.GetTenMHByMaMH(mamh);
            ViewBag.aaa = mamh;

            IList<KetQua> kq = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KetQuaAPI?mamh=" + mamh);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<KetQua>>();
                    readTask.Wait();

                    kq = readTask.Result;
                }
            }
            return View("Index", kq);
        }

        // Tạo form Create Kết Quả các môn học cho 1 sinh viên
        [Authorize(Roles = "admin")]
        public ActionResult Create(string masv)
        {
            var db = new QLSVContext();
            if (masv != null)
            {
                ViewBag.MaSV = new SelectList(db.SinhViens.Where(s => s.MaSV == masv).ToList(), "MaSV", "HoTen");
                var test = db.KetQuas.Where(k => k.MaSV == masv).Select(k => k.MaMH).ToList();
                ViewBag.MaMH = new SelectList(db.MonHocs.Where(m => !test.Contains(m.MaMH)), "MaMH", "TenMH");
                ViewBag.aaa = masv;
            }
            return View();
        }

        // Tạo form Create Kết Quả tất cả sinh viên của 1 môn học
        [Authorize(Roles = "user")]
        public ActionResult CreateFromMH(string mamh)
        {
            var db = new QLSVContext();
            if (mamh != null)
            {
                ViewBag.MaMH = new SelectList(db.MonHocs.Where(m => m.MaMH == mamh), "MaMH", "TenMH");
                var test = db.KetQuas.Where(k => k.MaMH == mamh).Select(k => k.MaSV).ToList();
                ViewBag.MaSV = new SelectList(db.SinhViens.Where(s => !test.Contains(s.MaSV)), "MaSV", "HoTen");
                ViewBag.aaa = mamh;
            }
            return View("Create");
        }

        // Create Kết Quả các môn học cho 1 sinh viên
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(KetQua kq)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<KetQua>("KetQuaAPI", kq);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("IndexByMaSinhVien", new { masv = kq.MaSV });
                    }
                }

            }
            var db = new QLSVContext();
            if (kq.MaSV != null)
            {
                ViewBag.MaSV = new SelectList(db.SinhViens.Where(s => s.MaSV == kq.MaSV).ToList(), "MaSV", "HoTen");
                var test = db.KetQuas.Where(k => k.MaSV == kq.MaSV).Select(k => k.MaMH).ToList();
                ViewBag.MaMH = new SelectList(db.MonHocs.Where(m => !test.Contains(m.MaMH)), "MaMH", "TenMH", kq.MaMH);
                ViewBag.aaa = kq.MaSV;
            }

            return View(kq);
        }

        // Create Kết Quả tất cả sinh viên của 1 môn học
        [Authorize(Roles = "user")]
        [HttpPost]
        public ActionResult CreateFromMH(KetQua kq)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<KetQua>("KetQuaAPI", kq);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("IndexByMaMonHoc", new { mamh = kq.MaMH });
                    }
                }

            }
            var db = new QLSVContext();
            if (kq.MaMH != null)
            {
                ViewBag.MaMH = new SelectList(db.MonHocs.Where(m => m.MaMH == kq.MaMH), "MaMH", "TenMH");
                var test = db.KetQuas.Where(k => k.MaMH == kq.MaMH).Select(k => k.MaSV).ToList();
                ViewBag.MaSV = new SelectList(db.SinhViens.Where(s => !test.Contains(s.MaSV)), "MaSV", "HoTen", kq.MaSV);
                ViewBag.aaa = kq.MaMH;
            }

            return View("Create", kq);
        }

        // Tạo form Edit Kết Quả
        [Authorize(Roles = "admin, user")]
        public ActionResult Edit(int STT)
        {
            KetQua kq = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KetQuaAPI?stt=" + STT);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<KetQua>();
                    readTask.Wait();

                    kq = readTask.Result;
                }
            }

            var db = new QLSVContext();
            ViewBag.MaSV = new SelectList(db.SinhViens, "MaSV", "HoTen", kq.MaSV);
            ViewBag.MaMH = new SelectList(db.MonHocs, "MaMH", "TenMH", kq.MaMH);
            ViewBag.aaa = kq.MaSV;

            FormsIdentity id = (FormsIdentity)User.Identity;
            FormsAuthenticationTicket ticket = id.Ticket;
            var data = ticket.UserData;

            string gv = data.Split(",".ToCharArray())[0];
            if (gv != "admin")
                ViewBag.aaa = kq.MaMH;

            return View(kq);
        }

        // Edit Kết Quả
        [Authorize(Roles = "admin, user")]
        [HttpPost]
        public ActionResult Edit(KetQua kq)
        {
            FormsIdentity id = (FormsIdentity)User.Identity;
            FormsAuthenticationTicket ticket = id.Ticket;
            var data = ticket.UserData;

            string gv = data.Split(",".ToCharArray())[0];

            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var putTask = client.PutAsJsonAsync<KetQua>("KetQuaAPI", kq);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        if (gv != "admin")
                            return RedirectToAction("IndexByMaMonHoc", new { mamh = kq.MaMH });
                        return RedirectToAction("IndexByMaSinhVien", new { masv = kq.MaSV });
                    }
                }
            }

            var db = new QLSVContext();
            ViewBag.MaSV = new SelectList(db.SinhViens, "MaSV", "HoTen", kq.MaSV);
            ViewBag.MaMH = new SelectList(db.MonHocs, "MaMH", "TenMH", kq.MaMH);
            ViewBag.aaa = kq.MaSV;
            if (gv != "admin")
                ViewBag.aaa = kq.MaMH;

51800882_51800187_QLSinhVien/Controllers/KhoaController.cs
using _51800882_51800187_QLSinhVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using _51800882_51800187_QLSinhVien.Res;

namespace _51800882_51800187_QLSinhVien.Controllers
{
    public class KhoaController : Controller
    {
        // GET: Khoa
        KhoaDAO dao = new KhoaDAO(new QLSVContext());
        string apiUrl = "https://localhost:44328/api/";

        // Danh sách Khoa
        [Authorize(Roles = "admin, user")]
        public ActionResult Index()
        {
            IList<Khoa> khoas = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KhoaAPI");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Khoa>>();
                    readTask.Wait();

                    khoas = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
            }
            return View(khoas);
        }

        // Tạo form Create Khoa
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // Tạo Khoa
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(Khoa kh)
        {
            if (ModelState.IsValid)
            {
                var isExists = dao.GetByID(kh.MaKhoa);

                if (isExists == null)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(apiUrl);

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<Khoa>("KhoaAPI", kh);
                        postTask.Wait();

                        var result = postTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, LangResource.messExistsFacultyID);
                }
            }
            return View(kh);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            Khoa kh = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("KhoaAPI?id=" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<Khoa>();
                    readTask.Wait();

                    kh = readTask.Result;
                }
            }

            return View(kh);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(Khoa kh)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var putTask = client.PutAsJsonAsync<Khoa>("KhoaAPI", kh);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(kh);
        }

        // Xóa Khoa
        //public ActionResult Delete(String id)
        //{
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri(apiUrl);

        //        //HTTP DELETE
        //        var deleteTask = client.DeleteAsync("KhoaAPI/" + id);
        //        deleteTask.Wait();

        //        var result = deleteTask.Result;
        //        if (result.IsSuccessStatusCode)
        //        {

        //            return RedirectToAction("Index");
        //        }
        //    }

        //    return RedirectToAction("Index");
        //}
    }
}

51800882_51800187_QLSinhVien/Views/SinhVien/Create.cshtml
@model _51800882_51800187_QLSinhVien.Models.SinhVien

@{
    ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.create;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@_51800882_51800187_QLSinhVien.Res.LangResource.student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MaSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioiTinh", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Khoa.TenKhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKhoa", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@_51800882_51800187_QLSinhVien.Res.LangResource.create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

51800882_51800187_QLSinhVien/Views/SinhVien/Edit.cshtml
@model _51800882_51800187_QLSinhVien.Models.SinhVien

@{
    ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.edit;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@_51800882_51800187_QLSinhVien.Res.LangResource.student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control", @readonly="true"} })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GioiTinh", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Khoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKhoa", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhoa, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@_51800882_51800187_QLSinhVien.Res.LangResource.edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

51800882_51800187_QLSinhVien/Views/SinhVien/Index.cshtml
@model IEnumerable<_51800882_51800187_QLSinhVien.Models.SinhVien>

@{
    if (ViewBag.Loai == 0)
    {
        ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.studentList;
    }
    else
    {
        ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.studentListForFaculty;
    }
}

<h2 class="text-center" style="text-transform:uppercase">@ViewBag.Title <b>@ViewBag.TenKhoa</b></h2>

<div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
    @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
    {

        <p>
            <a href='@Url.Action("Create")' class="btn btn-primary">@_51800882_51800187_QLSinhVien.Res.LangResource.create</a>
        </p>
    }

    @Html.DropDownList("MaKhoa", null, "-- " + @_51800882_51800187_QLSinhVien.Res.LangResource.faculty + " --", new { @class = "form-control", @onChange = "SelectedValue(this)" })
</div>


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaSV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Khoa.TenKhoa)
            </th>
            @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
            {
                <th></th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MaSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoTen)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.NgaySinh)*@
                    @String.Format("{0:dd/MM/yyyy}", item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GioiTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Khoa.TenKhoa)

                </td>
                 @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
                {
                <td>
                    <a href='@Url.Action("Edit", new { id = item.MaSV })' class="btn btn-warning">@_51800882_51800187_QLSinhVien.Res.LangResource.edit</a>

                    <a href='#' class="btn btn-danger btn-remove" data_id="@item.MaSV" data_name="@item.HoTen">@_51800882_51800187_QLSinhVien.Res.LangResource.delete</a>

                    <a href='@Url.Action("IndexByMaSinhVien", "KetQua", new { masv = item.MaSV })' class="btn btn-success">@_51800882_51800187_QLSinhVien.Res.LangResource.checkResult</a>
                </td>
                 }
            </tr>
        }

    </table>

    @*@if (ViewBag.Loai == 1) {
            <div>
                @Html.ActionLink("Quay lại", "Index", "Khoa")
            </div>
        }*@

    @section scripts{
        <script>
            function SelectedValue(ddlObject) {
                //Selected value of dropdownlist
                var selectedValue = ddlObject.value;
                if (selectedValue != "") {
                    window.location.href = '/SinhVien/IndexByMaKhoa?makhoa=' + selectedValue;
                }
                else {
                    window.location.href = './Index';
                }

            }

            $(document).ready(function () {
                $('.btn-remove').click(function (e) {
                    e.preventDefault();
                    var atag = $(this);
                    var data_id = atag.attr('data_id');
                    var data_name = atag.attr('data_name');
                    if (!confirm('@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messQuestionDelete) ' + data_name + "?"))
                        return;
                    $.ajax(
                        {
                            url: 'https://localhost:44328/api/SinhVienAPI/' + data_id,
                            method: "DELETE",
                            success: function (data) {
                                atag.closest('tr').remove();
                                alert('@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messDeleteSuccess) ' + '@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.student) ' + data_name);
                                return;
                            },
                            error: function () {
                                alert('@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messDeleteError) ' + '@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.student) ' + data_name + '@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messDeleteErrorStudent)');
                            }
                        }
                    );
                });
            });
        </script>
    }