51800882_51800187_QLSinhVien/Models/KetQua.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using _51800882_51800187_QLSinhVien.Res;

namespace _51800882_51800187_QLSinhVien.Models
{
    public class KetQua
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int STT { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredScore")]
        [Range(0, 10, ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messStringScore")]
        [Display(Name = "score", ResourceType = typeof(LangResource))]
        public int Diem { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredSubject")]
        [Display(Name = "subjectId", ResourceType = typeof(LangResource))]
        public string MaMH { get; set; }

        [ForeignKey("MaMH")]
        public virtual MonHoc MonHocs { get; set; }

        [Required(ErrorMessageResourceType = typeof(LangResource), ErrorMessageResourceName = "messRequiredStudent")]
        [Display(Name = "studentId", ResourceType = typeof(LangResource))]
        public string MaSV { get; set; }

        [ForeignKey("MaSV")]
        public virtual SinhVien SinhViens { get; set; }
    }
}

51800882_51800187_QLSinhVien/Controllers/MonHocController.cs
using _51800882_51800187_QLSinhVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using _51800882_51800187_QLSinhVien.Res;

namespace _51800882_51800187_QLSinhVien.Controllers
{
    public class MonHocController : Controller
    {
        // GET: MonHoc
        MonHocDAO dao = new MonHocDAO(new QLSVContext());
        string apiUrl = "https://localhost:44328/api/";

        // Danh sách môn học
        [Authorize(Roles = "admin, user")]
        public ActionResult Index()
        {
            IList<MonHoc> mh = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("MonHocAPI");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<MonHoc>>();
                    readTask.Wait();

                    mh = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
            }
            return View(mh);
        }

        // Danh sách môn học của một giảng viên dạy
        [Authorize(Roles = "user")]
        public ActionResult IndexByMaGV(string magv)
        {
            IList<MonHoc> mh = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("MonHocAPI?magv=" + magv);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<MonHoc>>();
                    readTask.Wait();

                    mh = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
            }
            return View("Index", mh);
        }

        // Tạo form Create MonHoc
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            return View();
        }

        // Create MonHoc
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(MonHoc mh)
        {
            if (ModelState.IsValid)
            {
                var isExists = dao.GetByID(mh.MaMH);

                if (isExists == null)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(apiUrl);

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<MonHoc>("MonHocAPI", mh);
                        postTask.Wait();

                        var result = postTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, LangResource.messExistsSubjectID);
                }
            }
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", mh.MaKhoa);
            return View(mh);
        }

        // Tạo form Edit MonHoc
        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            MonHoc mh = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("MonHocAPI?id=" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<MonHoc>();
                    readTask.Wait();

                    mh = readTask.Result;
                }
            }
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", mh.MaKhoa);

            return View(mh);
        }

        // Edit MonHoc
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(MonHoc mh)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var putTask = client.PutAsJsonAsync<MonHoc>("MonHocAPI", mh);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", mh.MaKhoa);
            return View(mh);
        }
    }
}

51800882_51800187_QLSinhVien/Controllers/SinhVienController.cs
using _51800882_51800187_QLSinhVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using _51800882_51800187_QLSinhVien.Res;

namespace _51800882_51800187_QLSinhVien.Controllers
{
    public class SinhVienController : Controller
    {
        // GET: SinhVien
        SinhVienDAO dao = new SinhVienDAO(new QLSVContext());
        string apiUrl = "https://localhost:44328/api/";

        // Danh sách sinh viên
        [Authorize(Roles = "admin, user")]
        public ActionResult Index()
        {
            ViewBag.Loai = 0;
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");
            IList<SinhVien> sv = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("SinhVienAPI");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SinhVien>>();
                    readTask.Wait();

                    sv = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
            }
            return View(sv);
        }

        // Danh sách sinh viên lọc theo Khoa
        [Authorize(Roles = "admin, user")]
        public ActionResult IndexByMaKhoa(string makhoa)
        {
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", makhoa);
            KhoaDAO khoadao = new KhoaDAO(new QLSVContext());
            ViewBag.Loai = 1;
            ViewBag.TenKhoa = khoadao.GetTenKhoaByMaKhoa(makhoa);
            IList<SinhVien> sv = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("SinhVienAPI?makhoa=" + makhoa);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<SinhVien>>();
                    readTask.Wait();

                    sv = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error. Please contact admin.");
                }
            }
            return View("Index", sv);
        }

        // Tạo form Create SV
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa");

            List<SelectListItem> GioiTinh = new List<SelectListItem>() {
                new SelectListItem(){Text="Nam", Value="Nam"},
                new SelectListItem(){Text="Nữ", Value="Nữ"}
            };

            ViewBag.GioiTinh = new SelectList(GioiTinh, "Value", "Text");

            return View();
        }

        // Create SV
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(SinhVien sv)
        {
            if (ModelState.IsValid)
            {
                var isExists = dao.GetByID(sv.MaSV);

                if (isExists == null)
                {
                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(apiUrl);

                        //HTTP POST
                        var postTask = client.PostAsJsonAsync<SinhVien>("SinhVienAPI", sv);
                        postTask.Wait();

                        var result = postTask.Result;
                        if (result.IsSuccessStatusCode)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, LangResource.messExistsStudentID);
                }
            }
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", sv.MaKhoa);
            List<SelectListItem> GioiTinh = new List<SelectListItem>() {
                new SelectListItem(){Text="Nam", Value="Nam"},
                new SelectListItem(){Text="Nữ", Value="Nữ"}
            };

            ViewBag.GioiTinh = new SelectList(GioiTinh, "Value", "Text", sv.GioiTinh);

            return View(sv);
        }

        // Tạo form Edit SV
        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            SinhVien sv = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(apiUrl);
                //HTTP GET
                var responseTask = client.GetAsync("SinhVienAPI?id=" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<SinhVien>();
                    readTask.Wait();

                    sv = readTask.Result;
                }
            }

            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", sv.MaKhoa);
            List<SelectListItem> GioiTinh = new List<SelectListItem>() {
                new SelectListItem(){Text="Nam", Value="Nam"},
                new SelectListItem(){Text="Nữ", Value="Nữ"}
            };

            ViewBag.GioiTinh = new SelectList(GioiTinh, "Value", "Text", sv.GioiTinh);



            return View(sv);
        }

        // Edit SV
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(SinhVien sv)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(apiUrl);

                    //HTTP POST
                    var putTask = client.PutAsJsonAsync<SinhVien>("SinhVienAPI", sv);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            var db = new QLSVContext();
            ViewBag.MaKhoa = new SelectList(db.Khoas, "MaKhoa", "TenKhoa", sv.MaKhoa);
            List<SelectListItem> GioiTinh = new List<SelectListItem>() {
                new SelectListItem(){Text="Nam", Value="Nam"},
                new SelectListItem(){Text="Nữ", Value="Nữ"}
            };

            ViewBag.GioiTinh = new SelectList(GioiTinh, "Value", "Text", sv.GioiTinh);
            return View(sv);
        }
    }
}

51800882_51800187_QLSinhVien/Views/KetQua/Create.cshtml
@model _51800882_51800187_QLSinhVien.Models.KetQua

@{
    ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.create;
    FormsIdentity id = (FormsIdentity)User.Identity;
    FormsAuthenticationTicket ticket = id.Ticket;
    var data = ticket.UserData;

    string iid = data.Split(",".ToCharArray())[1];
    string gv = data.Split(",".ToCharArray())[0];
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@_51800882_51800187_QLSinhVien.Res.LangResource.result</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MonHocs.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaMH", null, new { @class = "form-control" })
                @*@Html.EditorFor(model => model.MonHocs.TenMH, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.MaMH } })*@
                @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinhViens.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSV", null, new { @class = "form-control" })
                @*@Html.EditorFor(model => model.SinhViens.HoTen, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.MaSV } })*@
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@_51800882_51800187_QLSinhVien.Res.LangResource.create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Quay lại", "Index")*@
    @if (gv == "admin")
    {
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "IndexByMaSinhVien", new { masv = ViewBag.aaa })
    }
    else
    {
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "IndexByMaMonHoc", new { mamh = ViewBag.aaa })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

51800882_51800187_QLSinhVien/Views/KetQua/Edit.cshtml
@model _51800882_51800187_QLSinhVien.Models.KetQua

@{
    ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.edit;
    FormsIdentity id = (FormsIdentity)User.Identity;
    FormsAuthenticationTicket ticket = id.Ticket;
    var data = ticket.UserData;

    string iid = data.Split(",".ToCharArray())[1];
    string gv = data.Split(",".ToCharArray())[0];
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@_51800882_51800187_QLSinhVien.Res.LangResource.result</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.STT)

        <div class="form-group">
            @Html.LabelFor(model => model.MonHocs.TenMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaMH", null, new { @class = "form-control", @readonly = "@readonly", @style= "pointer-events:none;touch-action: none;" })
                @Html.ValidationMessageFor(model => model.MaMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SinhViens.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSV", null, new { @class = "form-control", @readonly = "readonly", @style = "pointer-events:none;touch-action: none;" })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diem, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@_51800882_51800187_QLSinhVien.Res.LangResource.edit class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Quay lại", "Index")*@
    @if (gv == "admin")
    {
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "IndexByMaSinhVien", new { masv = ViewBag.aaa })
    }
    else
    {
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "IndexByMaMonHoc", new { mamh = ViewBag.aaa })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

51800882_51800187_QLSinhVien/Views/KetQua/Index.cshtml
@model IEnumerable<_51800882_51800187_QLSinhVien.Models.KetQua>

@{
    if (ViewBag.Loai == 0)
    {
        ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.resultList;
        <h2 style="text-transform:uppercase" class="text-center" style="text-transform:uppercase">@ViewBag.Title</h2>
    }
    else if (ViewBag.Loai == 1)
    {
        ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.resultForStudent;
        <h2 style="text-transform:uppercase" class="text-center" style="text-transform:uppercase">@ViewBag.Title <b>@ViewBag.TenSV</b></h2>
    }
    else
    {
        ViewBag.Title = _51800882_51800187_QLSinhVien.Res.LangResource.resultListForSubject;
        <h2 style="text-transform:uppercase" class="text-center" style="text-transform:uppercase">@ViewBag.Title <b>@ViewBag.TenMH</b></h2>
    }
    var STT = 1;
    FormsIdentity id = (FormsIdentity)User.Identity;
    FormsAuthenticationTicket ticket = id.Ticket;
    var data = ticket.UserData;

    string gv = data.Split(",".ToCharArray())[0];
}


<div style="display: flex; justify-content: space-between; margin-bottom: 20px;">

    @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
    {
        if (ViewBag.Loai == 1)
        {
            <p>
                <a href='@Url.Action("Create", new { masv = ViewBag.MaSV })' class="btn btn-primary">@_51800882_51800187_QLSinhVien.Res.LangResource.create</a>
            </p>
        }
        else
        {
            @Html.DropDownList("MaMH", null, "-- " + @_51800882_51800187_QLSinhVien.Res.LangResource.subject + " --", new { @class = "form-control", @onChange = "SelectedValue(this)" })
        }
    }

    @if (Roles.IsUserInRole(User.Identity.Name, "user"))
    {
        if (ViewBag.Loai == 2)
        {
            <p>
                <a href='@Url.Action("CreateFromMH", new { mamh = ViewBag.aaa })' class="btn btn-primary">@_51800882_51800187_QLSinhVien.Res.LangResource.create</a>
            </p>
        }

    }


</div>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

<table class="table table-bordered">
    <tr>
        <th>
            STT
        </th>
        @if (ViewBag.Loai != 2)
        {
            <th>
                @Html.DisplayNameFor(model => model.MonHocs.TenMH)
            </th>
        }
        @if (ViewBag.Loai != 1)
        {
            <th>
                @Html.DisplayNameFor(model => model.SinhViens.HoTen)
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.Diem)
        </th>
        @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @STT
            </td>
            @if (ViewBag.Loai != 2)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.MonHocs.TenMH)
                </td>
            }
            @if (ViewBag.Loai != 1)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.SinhViens.HoTen)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.Diem)
            </td>

            <td>
                @if (Roles.IsUserInRole(User.Identity.Name, "admin"))
                {
                    if (ViewBag.Loai == 1)
                    {
                        <a href='@Url.Action("Edit", new { stt = item.STT })' class="btn btn-warning">@_51800882_51800187_QLSinhVien.Res.LangResource.edit</a>
                    }
                }
                else
                {
                    <a href='@Url.Action("Edit", new { stt = item.STT })' class="btn btn-warning">@_51800882_51800187_QLSinhVien.Res.LangResource.edit</a>
                }

                <a href='#' class="btn btn-danger btn-remove" data_id="@item.STT" data_name_mh="@item.MonHocs.TenMH" data_name_sv="@item.SinhViens.HoTen">@_51800882_51800187_QLSinhVien.Res.LangResource.delete</a>
            </td>

        </tr>
        STT++;
    }

</table>

@if (ViewBag.Loai == 1)
{
    <div>
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "Index", "SinhVien")
    </div>
}

@if (Roles.IsUserInRole(User.Identity.Name, "user"))
{
    if (ViewBag.Loai == 2)
    {
        @Html.ActionLink(_51800882_51800187_QLSinhVien.Res.LangResource.back, "IndexByMaGV", "MonHoc", new { magv = @gv }, null)
    }
}

@section scripts{
    <script>
        function SelectedValue(ddlObject) {
            //Selected value of dropdownlist
            var selectedValue = ddlObject.value;
            if (selectedValue != "") {
                window.location.href = '/KetQua/IndexByMaMonHoc?mamh=' + selectedValue;
            }
            else {
                window.location.href = './Index';
            }
        }

        $(document).ready(function () {
            $('.btn-remove').click(function (e) {
                e.preventDefault();
                var atag = $(this);
                var data_id = atag.attr('data_id');
                var data_name_mh = atag.attr('data_name_mh');
                var data_name_sv = atag.attr('data_name_sv');
                if (!confirm('@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messQuestionDelete) ' + '@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.result) ' + data_name_mh + ' - ' + data_name_sv + "?"))
                    return;
                $.ajax(
                    {
                        url: 'https://localhost:44328/api/KetQuaAPI/' + data_id,
                        method: "DELETE",
                        success: function (data) {
                            atag.closest('tr').remove();
                            alert('@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.messDeleteSuccess) ' + '@Html.Raw(@_51800882_51800187_QLSinhVien.Res.LangResource.result) ' + data_name_mh + ' - ' + data_name_sv);
                            return;
                        },
                        failed: function () {

                        }
                    }
                );
            });
        });
    </script>
}